language: java
sudo: false
jdk:
    -openjdk8
addons:
  sonarcloud:
    organization: "malavasiale"
    token: "b04127c78afa9879cb3c6803226cc88b4feacba0"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
   - mvn clean package sonar:sonar -Dsonar.projectKey=malavasiale_tajo

